feat(action): update working directory and enhance PR messages for validation and plan outputs

diff --git a/.github/actions/tofu_plan_lint/action.yml b/.github/actions/tofu_plan_lint/action.yml
--- a/.github/actions/tofu_plan_lint/action.yml
+++ b/.github/actions/tofu_plan_lint/action.yml
@@ -20,7 +20,7 @@ outputs:
 
 runs:
   using: 'composite'
-  working-directory: './tofu'
+  working-directory: ${{ inputs.tofu_directory }}
   steps:
 
     - name: Set Up Opentofu
@@ -36,13 +36,67 @@ runs:
       run: tofu validate -no-color
       shell: bash
       continue-on-error: true
+
+    - name: OpenTofu PR Message
+      uses: 'mshick/add-pr-comment@v2'
+      if: ${{ steps.validate.outputs.stderr }}
+      with :
+        refresh-message-position: true
+        message-id: ${{ github.event.pull_request.id }}-VALIDATE
+        message: |
+          ### ⚠️ OpenTofu Validation Failed 🛠️
+          There's some issues, homeboy!. Click below to view the details:
+          <details>
+          <summary>🔍 View OpenTofu Validate Output</summary>
+
+          ```
+          ${{ steps.validate.outputs.stdout }}
+          ```
+
+          </details>
+          
+            ${{ steps.validate.outputs.stderr && format('<details>\n<summary>🔍 View OpenTofu Stderr </summary>\n\n```\n{0}\n```\n\n</details>', steps.validate.outputs.stderr) }}
+
+          Keep trying, Kiddo! 🚀
+        message-failure: |
+          Errors detected in the OpenTofu plan step. Please check the logs for details.
     
     - name: OpenTofu Plan
       id: plan
       run: tofu plan -no-color
       shell: bash
       continue-on-error: true
+
+    - name: OpenTofu PR Message
+      uses: 'mshick/add-pr-comment@v2'
+      with :
+        refresh-message-position: true
+        message-id: ${{ github.event.pull_request.id }}-PLAN
+        message: |
+          ### 🚀 OpenTofu Plan Output
+          The OpenTofu plan has been successfully generated. Click below to view the details:
+          <details>
+          <summary>🔍 View OpenTofu Plan</summary>
+
+          ```
+          ${{ steps.plan.outputs.stdout }}
+          ```
+
+          </details>
+
+          ${{ steps.plan.outputs.stderr && format('<details>\n  <summary>🔍 View OpenTofu Plan Stderr</summary>\n\n  ```
+            {0}
+            ```  \n\n</details>', steps.plan.outputs.stderr) }}
+
+          Deploy when it;s good, Kiddo! 🚀
+        message-failure: |
+          Errors detected in the OpenTofu plan step. Please check the logs for details.
     
-    
+    - name: Potential Failure        
+      if: ${{ steps.validate.outputs.stderr }} || ${{ steps.plan.outputs.stderr }} 
+      run: |
+        echo "Errors found in Validation Or Plan. Failing the job."
+        echo ${{ steps.fmt.outputs.stderr }}
+        exit 1
 
     
