refactor(workflows): add error checking for formatting step in tf-pr-plan

diff --git a/.github/workflows/tf-pr-plan.yml b/.github/workflows/tf-pr-plan.yml
--- a/.github/workflows/tf-pr-plan.yml
+++ b/.github/workflows/tf-pr-plan.yml
@@ -33,7 +33,13 @@ jobs:
       run: |
         OUTPUT=$(find ./tofu -mindepth 1 -type d -exec tofu fmt -check {} \; | wc -l)
         echo "tofu_fmt_count=$OUTPUT" >> $GITHUB_ENV
+      shell: bash
 
+    - name: Check for Errors in Formatting Step
+      if: steps.fmt.outputs.stderr != ''
+      run: |
+        echo "Formatting error detected: ${{ steps.fmt.outputs.stderr }}"
+        exit 1
       shell: bash
     
     - name: Conditionally Run if Formatting Issues Exist
@@ -56,6 +62,7 @@ jobs:
         committer_email: actions@github.com
         message: 'Fix formatting issues'
         add: 'tofu/**'
+
   tofu_plan:
     runs-on: ubuntu-latest
     needs: setup
